# Generated by Django 5.1.4 on 2025-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=100)),
            ],
        ),
    ]
