# Generated by Django 5.1.4 on 2025-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='sector',
            new_name='sektor',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='jurisdiction',
        ),
        migrations.AddField(
            model_name='userdata',
            name='jurysdykcja',
            field=models.CharField(choices=[('RODO', 'Rozporządzenie Ogólne o Ochronie Danych (RODO)'), ('GDPR', 'General Data Protection Regulation (GDPR)'), ('CCPA', 'California Consumer Privacy Act (CCPA)'), ('HIPAA', 'Health Insurance Portability and Accountability Act (HIPAA)'), ('INNE', 'Inne')], default='RODO', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='typ_danych',
            field=models.CharField(choices=[('Personal Data', 'Dane osobowe'), ('Financial Data', 'Dane finansowe'), ('Health Data', 'Dane zdrowotne'), ('Biometric Data', 'Dane zdrowotne'), ('Location Data', 'Dane lokalizacyjne'), ('Login Data', 'Dane logowania'), ('Employee Data', 'Dane pracownicze'), ('Educational Data', 'Dane pracownicze'), ('Children Data', 'Dane dzieci'), ('Citizenship Data', 'Dane obywatelstwa'), ('Criminal Data', 'Dane kryminalne'), ('Technological Data', 'Dane technologiczne'), ('Research Data', 'Dane badawcze'), ('Political or Religious Data', 'Dane polityczne lub religijne')], default='Personal Data', max_length=100),
        ),
    ]
