# Generated by Django 5.1.4 on 2025-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_rename_sector_userdata_sektor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='typ_danych',
            field=models.CharField(choices=[('Personal Data', 'Dane osobowe'), ('Financial Data', 'Dane finansowe'), ('Health Data', 'Dane zdrowotne'), ('Biometric Data', 'Dane biometryczne'), ('Location Data', 'Dane lokalizacyjne'), ('Login Data', 'Dane logowania'), ('Employee Data', 'Dane pracownicze'), ('Educational Data', 'Dane edukacyjne'), ('Children Data', 'Dane dzieci'), ('Citizenship Data', 'Dane obywatelstwa'), ('Criminal Data', 'Dane kryminalne'), ('Technological Data', 'Dane technologiczne'), ('Research Data', 'Dane badawcze'), ('Political or Religious Data', 'Dane polityczne lub religijne')], default='Personal Data', max_length=100),
        ),
    ]
