# Generated by Django 5.1.4 on 2025-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0003_alter_userdata_typ_danych'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='jurysdykcja',
            field=models.CharField(choices=[('RODO', 'Rozporządzenie Ogólne o Ochronie Danych (RODO)'), ('GDPR', 'General Data Protection Regulation (GDPR)'), ('ISO/IEC 27701', 'Międzynarodowy standard zarządzania ochroną danych (ISO/IEC 27701)'), ('ANPD', 'Autoridade Nacional de Proteção de Dados (Brazylia)'), ('APPI', 'Act on the Protection of Personal Information (Japonia)'), ('Bundesdatenschutzgesetz (Niemcy)', 'Bdsg'), ('CALOPPA', 'California Online Privacy Protection Act (USA)'), ('CPA', 'Colorado Privacy Act'), ('CCPA', 'California Consumer Privacy Act (CCPA)'), ('CCPR', 'Consumer Credit Protection Regulation (Australia)'), ('CORPA', "Chilldren's Online Privacy Protection Act (USA)"), ('Data Protection Act (Wielka Brytania)', 'Dpa'), ('FADP', 'Federal Act on Data Protection (Szwajcaria)'), ('FERPA', 'Family Educational Rights and Privacy Act (USA)'), ('GDPL', 'General Data Protection Law (Chiny)'), ('HIPAA', 'Health Insurance Portability and Accountability Act (HIPAA)'), ('INDIA-DPDP', 'Digital Personal Data Protection Act (Indie)'), ('KVKK', 'Kişisel Verilerin Korunması Kanunu (Turcja)'), ('LGPD', 'Lei Geral de Proteção de Dados (Brazylia)'), ('NZPA', 'New Zealand Privacy Act'), ('PDPA', 'Personal Data Protection Act (Singapur)'), ('PDPO', 'Personal Data (Privacy) Ordinance (Hongkong)'), ('PIPEDA', 'Personal Information Protection and Electronic Documents Act (Kanada)'), ('POPIA', 'Protection of Personal Information Act (RPA)'), ('SOX', 'Sarbanes-Oxley Act (USA)'), ('VCDPA', 'Virginia Consumer Data Protection Act'), ('INNE', 'Inne')], default='RODO', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sektor',
            field=models.CharField(choices=[('Administracja', 'Sektor Administracji Publicznej'), ('Agrobiznes', 'Sektor Agrobiznesu'), ('Nauka', 'Sektor Badawczy i Naukowy'), ('Budownictwo', 'Sektor Budowlany i Inżynieryjny'), ('Edukacja', 'Sektor Edukacyjny'), ('Energia', 'Sektor Energii i Usług Komunalnych'), ('Finanse', 'Sektor Finansowy'), ('Handel', 'Sektor Handlowy i E-commerce'), ('Logistyka', 'Sektor Logistyczny i Transportowy'), ('Lotnictwo', 'Sektor Lotniczy i Kosmiczny'), ('Marketing', 'Sektor Marketingu i Reklamy'), ('Media', 'Sektor Mediów i Rozrywki'), ('Medycyna', 'Sektor Medyczny'), ('Moda', 'Sektor Mody i Urody'), ('Motoryzacja', 'Sektor Motoryzacyjny'), ('Nieruchomości', 'Sektor Nieruchomości'), ('Środowisko', 'Sektor Ochrony Środowiska'), ('Non-Profit', 'Sektor Organizacji Non-Profit'), ('Ochrona', 'Sektor Prywatnych Usług Ochrony'), ('Prawo', 'Sektor Prawny i Usług Profesjonalnych'), ('Produkcja', 'Sektor Produkcji'), ('Sztuka', 'Sektor Sztuki i Projektowania'), ('Sport', 'Sektor Sportowy i Rekreacyjny'), ('Telekomunikacja', 'Sektor Telekomunikacyjny'), ('Podróże', 'Sektor Turystyczny i Hotelarski'), ('Rolnictwo', 'Sektor Rolniczy'), ('Technologie', 'Sektor Technologiczny'), ('Ubezpieczenia', 'Sektor Ubezpieczeń'), ('Zasoby Ludzkie', 'Sektor Zarządzania Zasobami Ludzkimi'), ('Żywność', 'Sektor Żywności i Napojów'), ('Inne', 'Inne')], default='Inne', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='typ_danych',
            field=models.TextField(help_text='Lista typów danych wrażliwych w formacie JSON.'),
        ),
    ]
