# Generated by Django 5.1 on 2024-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lyric', models.TextField()),
                ('mood', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
